name: app_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  curved_navigation_bar: ^1.0.6
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  geocoding: ^3.0.0
  go_router: ^14.2.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  http: ^1.2.1
  flutter_secure_storage: ^5.0.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  path: ^1.9.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_speed_dial: ^6.1.0
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  visibility_detector: ^0.4.0+2
  timeago: ^3.7.0
  table_calendar: ^3.0.1
  test: ^1.25.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo_TI_Mobile.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

