// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxu3UcQUjiFRLOYSunKvV3ZKOLvdnNHEU',
    appId: '1:605915056852:web:a527f41fcef571af62c941',
    messagingSenderId: '605915056852',
    projectId: 'projeto-pint-70fc6',
    authDomain: 'projeto-pint-70fc6.firebaseapp.com',
    storageBucket: 'projeto-pint-70fc6.appspot.com',
    measurementId: 'G-96KSGQ07TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVPPEti1gkk2KNERDUNl4WNqFdddNyaQk',
    appId: '1:605915056852:android:85892092ef99965a62c941',
    messagingSenderId: '605915056852',
    projectId: 'projeto-pint-70fc6',
    storageBucket: 'projeto-pint-70fc6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxu3UcQUjiFRLOYSunKvV3ZKOLvdnNHEU',
    appId: '1:605915056852:web:2e3b68e3572469fc62c941',
    messagingSenderId: '605915056852',
    projectId: 'projeto-pint-70fc6',
    authDomain: 'projeto-pint-70fc6.firebaseapp.com',
    storageBucket: 'projeto-pint-70fc6.appspot.com',
    measurementId: 'G-EZQPHPFE26',
  );
}
